# Generated by Django 3.0 on 2022-03-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220331_1350'),
    ]
            

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
